exclude:
  - node_modules
  - script

sass:
  style: :compressed

#theme: jekyll-theme-notion

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/xdanger/jekyll-theme-notion"

title: Jekyll Theme - Notion
description: Notion is a Jekyll theme for GitHub Pages inspired by https://Notion.so
